# Generated by Django 4.1.2 on 2024-07-04 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', pyuploadcare.dj.models.ImageField()),
                ('description', models.TextField(max_length=4000)),
                ('location', models.TextField(default='default_location', max_length=255)),
                ('no_of_persons', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Automatic', max_length=60)),
                ('price', models.FloatField()),
                ('phone_number', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('Private-hire', 'Car Owner'), ('Construction-hire', 'Mechanic/Garage'), ('Transport-hire', 'Spare Parts Retailer'), ('Agricultural-hire', 'Spare Parts Retailer'), ('Airport Transfer', 'Airport Transfer')], default='Private-hire', max_length=60)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
