# Generated by Django 4.1.2 on 2024-07-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Private-hire', 'Private-hire'), ('Construction-hire', 'Construction-hire'), ('Transport-hire', 'Transport-hire'), ('Agricultural-hire', 'Agricultural-hire'), ('Airport Transfer', 'Airport Transfer')], default='Private-hire', max_length=60),
        ),
    ]
