# Generated by Django 4.1.2 on 2024-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_car_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.TextField(default='Nairobi', max_length=255),
        ),
    ]
