# Generated by Django 5.0.7 on 2024-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_review_options_remove_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
