# Generated by Django 5.0.7 on 2024-08-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_car_name_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_back_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_front_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_number',
        ),
    ]
