# Generated by Django 5.0.7 on 2024-08-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_id_back_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
